name: Generate applet CAP and run python tests

on:
    workflow_dispatch:
    push:
      branches:
        - master
        - main
        - develop
    pull_request:

jobs:
  generate-and-test:
    runs-on: ubuntu-22.04
    name: Generate CAP and run tests

    container:
      image: docker.io/alexisgrojean/applet-builder:latest
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate CAP
        run: |
            ./generate_cap.sh -p "/home/devuser"
    
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: Setup tests environment
        run: |
            export GH_USER=${{ secrets.GH_USER }}
            export GH_TOKEN=${{ secrets.GH_TOKEN }}
            pdm lock -G github-actions
            pdm install -G github-actions
